### PR TITLE
Add simple tooltip for options

### PR DESCRIPTION
**Pull request by LaChope**
@ledsoft @blcham
This is the simplest way I found to add a tooltip for the options. This PR is related to https://github.com/kbss-cvut/s-forms/issues/347.

I chose `title` as prop name, as it is the standard attribute for [tooltip in HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title).

This looks like this on Chrome:

image

### CODE REVIEW

**Comment by blcham** [comment]
@LaChope does it behave well if title is null? (or it shows some kind of empty tooltip instead?)

**Comment by LaChope** [comment]
@blcham Yes, if `title` is null or does not exist, no tooltip is shown at all.

**Comment by blcham** [comment]
I see that we use options in SForms as follows:
```
    options[pValue["@id"]] = {
        id: pValue["@id"],
        value: pValue["@id"],
        label: label,
        title: comment,
        children: [],
      };
```
To me `title` is little confusing, i would prefer `description` (this I prefer) or `comment`. Let's wait for @ledsoft about this.

**Comment by blcham** [comment]
@LaChope Thus the key should be described here as well: https://github.com/lecbyjak/intelligent-tree-select?tab=readme-ov-file#intelligent-tree-select-props

**Comment by LaChope** [comment]
@ledsoft @blcham I implemented the required changes.

**Review by ledsoft — APPROVED** [review]
LGTM

**Pull request merged**
